### ISSUE TITLE
CommonJS Builds

### ISSUE THREAD

**Issue by mixonic** [bustlelabs/mobiledoc-html-renderer#7]
These should be enabled. We've done so already for [content-kit](https://github.com/bustlelabs/content-kit-editor/pull/194) and [mobiledoc-dom-renderer](https://github.com/bustlelabs/mobiledoc-dom-renderer/compare/f60bc902bc693ec3c25f4c17c4a110f4041036ee...955d8af4f09b5c81425a68a6b2e9a8deacb1a544)

**Comment by bantic** [comment]
This is now built for commonjs.
